# Generated by Django 3.2.5 on 2021-11-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_auto_20211123_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_People_person_friends_+', to='People.Person'),
        ),
    ]
